### ISSUE TITLE
add REST API for encrypting data

### ISSUE THREAD

**Issue by logicminds** [binford2k/binford2k-node_encrypt#1]
Thank you for making this, this is definitely needed  in secure environments.  The environment we are using is very secure, which means accessing systems with root access is a pain in the ass and can sometimes take a few days to get approval.  This means that encrypting data will be difficult in my environment.

Because you created a puppet face to encrypt that data I was hoping it would be possible to make that face available over the puppet REST API so that we can remotely encrypt data without having to log into the puppet CA as root.   I think this would be a killer feature because of the following:
- you still need a signed cert to make the request
- the end user can script or build a web ui around encrypting this data.

Example REST Endpoints:

```
curl -X PUT -d data:supersecret123'  --sslcert=mypuppet_signed_cert https://puppetca:8140/api/v3/node_encrypt

returns: encrypted data
```

The REST API endpoint should also be protected by auth.conf if possible in order to control access.

**Comment by logicminds** [comment]
@binford2k This doesn't really accomplish the goal but I do like the fact that encrypting data can at least by "load balanced" across masters in the future.  I would still need an API as I am encrypting this data from a javascript engine on the fly and inserting directly to hiera via gitlab API.  Because its javascript we try to only use REST API commands.

**Comment by binford2k** [comment]
I'm not convinced that a REST API fits the goals of this project--to be stupid-simple to configure and nearly transparent to use with few opportunities for things to break. Nevertheless, it would be fairly easy to build a new terminus exposing a REST API on top of this module and just use the library functions I'm exposing.

See https://github.com/richardc/puppet-datacat/pull/17/files for an example of how easy it would be to call the encryption routines.

I'm not going to close this. I might implement it at some point, if you don't get around to it. But it would probably be a separate module.

**Comment by binford2k** [comment]
This is out of scope.You're totally welcome to build an endpoint though, it would be pretty straightforward.
