### ISSUE TITLE
compare usage against puppet 4.6 Sensitive type

### ISSUE THREAD

**Issue by logicminds** [binford2k/binford2k-node_encrypt#11]
I doubt anybody is using 4.6 yet but interesting to see a similar type to node_encrypt and would like to see some documentation around the differences. 

```
2:>> $var1 = Sensitive.new('supersecret')
 => Sensitive [value redacted]
3:>> $var1 == 'supersecret'
 => false
4:>> $var1
 => Sensitive [value redacted]
5:>> 
```

**Comment by binford2k** [comment]
Currently the Sensitive type is persistently tagging values so that everywhere Puppet displays content (reports, Console, etc.) know not to display it. It does not yet encrypt within the catalog. I'll add something to the readme at some point :)
