### ISSUE TITLE
Error while evaluating a Function Call

### ISSUE THREAD

**Issue by alex-mesfin** [binford2k/binford2k-node_encrypt#14]
I am getting the following error:

> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/node_encrypt: no such file to load -- puppet_x/binford2k/node_encrypt at /etc/puppetlabs/code/environments/development/modules/node_encrypt/manifests/file.pp:63:18 at /etc/puppetlabs/code/environments/development/modules/crypto_tool/manifests/profile/helpers/create_sshkeys.pp:25 on node host.domain.com

and the resoure at issue is 

```
     node_encrypt::file { $ssh_file:
         #ensure  => 'file',
         content => $ssh_hash[$title],
         mode    => '0600',
         seltype => 'ssh_home_t',
      }
```

the file resource works fine with out the `node_encrypt::`
Any Idea why this not working ...

Thanks
Alex,

**Comment by binford2k** [comment]
This requires a single puppet run on the master to pluginsync before it can be used effectively. Are you still having issues?

**Comment by logicminds** [comment]
Also seeing this in the puppet-debugger when listing types.

**Comment by logicminds** [comment]
@alex-mesfin I suspect you might be running into #8  

I would see if installing this gem: https://github.com/logicminds/node_encrypt_gem on your puppetserver will fix the problem.

You want to install for both ruby and puppetserver jruby.  You also need to compile the gem since I have not pushed to rubygems.

`/opt/puppetlabs/puppet/bin/gem install node_encrypt`
`/opt/puppetlabs/puppet/bin/puppetserver gem install node_encrypt`

**Comment by nerdwit** [comment]
Hi, is there any resolution for this issue?  I'm getting the original error this issue was opened with on my catalog builds.  As far as I can tell, all the necessary files are in the right locations.

**Comment by olifre** [comment]
Hi, 
also hitting this... any new ideas on a potential fix? Does installing the gem resolve the issue? It seems the files are at the correct place...

**Comment by olifre** [comment]
Just submitted a PR which fixes this for me, and explains the underlying reason.
