### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jeefberkey** [binford2k/binford2k-node_encrypt#16]
I notice there have been a few bugfixes recently and was wondering if it was possible to release a new version of this module. 

We're looking at incorporating this into our project and it would be great to pull in a new tagged release before getting to work 😁

**Comment by Nekototori** [comment]
Yes please. Specifically when using the reduct function, the newest change to case sensitivity solves issues with classes not being found in a catalog.

**Comment by binford2k** [comment]
Done! Thanks for the reminder :)
