### ISSUE TITLE
Incompatibility of node_encrypt::certificates with Puppet 5

### ISSUE THREAD

**Issue by olifre** [binford2k/binford2k-node_encrypt#18]
Puppetserver log files show:
```
2017-09-27 18:02:51,273 ERROR [puppetserver] Puppet Denying find request for /file_metadata/public_certificates on fileserver mount 'public_certificates'. Use
 of auth directives for 'fileserver.conf' mount points is no longer supported. Remove these directives and use the 'auth.conf' file instead for access control.
2017-09-27 18:02:51,276 ERROR [puppetserver] Puppet Server Error: Not authorized to call find on /file_metadata/public_certificates with {:rest=>"public_certi
ficates", :links=>"manage", :checksum_type=>"md5", :source_permissions=>"ignore"}
```
So it seems that even though https://docs.puppet.com/puppet/5.2/config_file_fileserver.html#deprecated-security-directives still says that auth directives in `fileserver.conf` are only deprecated, they are actually not supported anymore. 
Trying with `allow *`, things work. 

I guess that to fix this correctly, https://github.com/puppetlabs/puppetlabs-puppet_authorization should be used to add an auth-stanza.

**Comment by ross-w** [comment]
Agh, just had this issue after upgrading PE to 2017.3.1 :(

**Comment by sammcj** [comment]
yeah still a major problem blocking us from upgrading our Puppet open source to 5.x and enterprise to 2017.3.1 as above 😡

**Comment by binford2k** [comment]
I'll get that handled today and push up a release.

**Comment by sammcj** [comment]
Legend!

Thank you!

--
Sam
