### ISSUE TITLE
Node_encrypt completely fails on PE 2017.3.1

### ISSUE THREAD

**Issue by ross-w** [binford2k/binford2k-node_encrypt#22]
Related to #18 but this issue is more fundamental.

When working around #18, it looks like the actual encryption is not working either.

As a minimal test case, when I run this (as per the README) on the master:
```
root@our-pe-master:~ 1 # puppet node encrypt -t fqdn-of.host "encrypt some text"
Warning: Setting trusted_server_facts is deprecated.
   (at /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1161:in `issue_deprecation_warning')
Error: password must be at least 4 bytes
Error: Try 'puppet help node encrypt' for usage
```

That error (password must be at least 4 bytes) looks like an OpenSSL error. I think what is happening is PE 2017.3.1 upgraded Ruby to 2.4, which comes with a very fussy OpenSSL gem, and node_encrypt is encountering the same issue as (for example) https://github.com/github/octocatalog-diff/issues/118

I was able to gem install the latest openssl gem (2.0.6) which appears to have relaxed the 4-byte requirement again, but if the code could be made compatible it would avoid such a hack

**Comment by olifre** [comment]
Hi!
Did you already try after this PR:
https://github.com/binford2k/binford2k-node_encrypt/pull/20
was applied? 
I had the same issue with non-enterprise Puppet 5 and implemented that as workaround. 

Indeed, https://github.com/ruby/openssl/commit/a896c3d1dfa090e92dec1abf8ac12843af6af721 seems to have fixed things on the OpenSSL-gem side, so maybe in a few years when we have Puppet 8 and Puppet 5 will have vanished, my workaround can be dropped again ;-).

**Comment by binford2k** [comment]
The specified command fails prior to applying #20 and succeeds after.

**Comment by ross-w** [comment]
Thanks everyone, I checked issues but missed the PR! You're way ahead of me
