### ISSUE TITLE
The logic to determine whether we're a CA is inflexible.

### ISSUE THREAD

**Issue by binford2k** [binford2k/binford2k-node_encrypt#25]
This code is *usually* correct, but not foolproof. We need a better way to do this.

https://github.com/binford2k/binford2k-node_encrypt/blob/260c22c7c098a493f77cc8988da660d2e38b60da/lib/puppet_x/binford2k/node_encrypt.rb#L15-L26

Thanks for the report @frizop

**Comment by frizop** [comment]
So I spent some time reading the code and checking on things and I'm still a bit confused.

I'm trying to run this site.pp, which classifies fine but doesn't compile on my master:

```
node default {
  node_encrypt::file { '/tmp/default':
    owner   => 'root',
    group   => 'root',
    content => 'This string will never appear in the catalog.',
  }
}
```

The way I read it, if the fqdn is the ca_server, then we're on the master and we should be using the CA cert, but that doesn't appear to be the result I get below:

```
root@puppet:/etc/puppetlabs/puppet/ssl# facter fqdn
puppet.local
root@puppet:/etc/puppetlabs/puppet/ssl# puppet config print ca_server
puppet.local
root@puppet:/etc/puppetlabs/puppet/ssl# puppet agent -tvd |& grep node_encrypt
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Need a node name to encrypt for at /etc/puppetlabs/code/environments/production/modules/node_encrypt/manifests/file.pp:63:18 at /etc/puppetlabs/code/environments/production/manifests/site.pp:5 on node puppet.local
```

**Comment by binford2k** [comment]
Dump out the `$clientcert` and see what's going on there.

```puppet
notify { 'clientcert':
    message => $clientcert,
}
```

We use the `clientcert` in the function call to encrypt: https://github.com/binford2k/binford2k-node_encrypt/blob/2636ba53904b31799c249f0c4f8b559f08481e08/lib/puppet/parser/functions/node_encrypt.rb#L12-L13

And then error if something besides a string is passed in: https://github.com/binford2k/binford2k-node_encrypt/blob/2636ba53904b31799c249f0c4f8b559f08481e08/lib/puppet_x/binford2k/node_encrypt.rb#L13

If you feel up to some ruby debugging, hit me up on slack sometime and we can poke at it a bit.

**Comment by frizop** [comment]
Hmm, so the clientcert looks fine from the agent side, ie: it's named properly.

```
root@765778d34c7b:/# puppet apply
notify { 'clientcert':
    message => $clientcert,
}
Notice: Compiled catalog for 765778d34c7b.local in environment production in 0.06 seconds
Notice: 765778d34c7b.local
Notice: /Stage[main]/Main/Notify[clientcert]/message: defined 'message' as '765778d34c7b.local'
Notice: Applied catalog in 0.08 seconds
```
On the master, I find the signed cert:

```
root@puppet:/etc/puppetlabs/puppet# tree -L 3 ssl
ssl
|-- ca
|   |-- ca_crl.pem
|   |-- ca_crt.pem
|   |-- ca_key.pem
|   |-- ca_pub.pem
|   |-- inventory.txt
|   |-- private
|   |-- requests
|   |-- serial
|   `-- signed
|       |-- 6ad80f5ba749.local.pem
|       |-- 765778d34c7b.local.pem
|       |-- 7e14eaf12caa.local.pem
|       |-- puppet.local.pem
|       `-- puppetdb.pem
|-- certificate_requests
|-- certs
|   |-- 6ad80f5ba749.local.pem
|   |-- ca.pem
|   `-- puppet.local.pem
|-- crl.pem
|-- private
|-- private_keys
|   `-- puppet.local.pem
`-- public_keys
    `-- puppet.local.pem

9 directories, 17 files
```

I'll try to hit you up on slack soon

**Comment by jradmacher** [comment]
I ran into the Problem yesterday: Our CA **and** puppet server was handled like a compile master.
The default server name was still present, which worked, because we have a CNAME in DNS:
`ca_server = puppet`

While debugging I looked at the possible checks:
- fqdn =Puppet.settings[:ca_server] => fails when using cnames 
- check if the CA exists in /etc/puppetlabs/puppet/ssl/ca/ => could be an old CA
- check if the certificate file exists in /etc/puppetlabs/puppet/ssl/ca/[signed,request]/ => could be an old CA
- check if the 'clientcert' is signed by the CA  in /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem => Sure way to detect, if the found CA is the active CA. But the clientcert must be checked, if it is signed at all.
