### ISSUE TITLE
node_encrypt::certificates fails on CA-server for Puppet Enterprise: Unknown resource type: 'puppet_authorization::rule'

### ISSUE THREAD

**Issue by georgehansper** [binford2k/binford2k-node_encrypt#27]
We are using this module (node_encrypt) with Puppet Enterprise 2017.3.1

When running puppet on the CA server (puppetmaster), the following error occurs when the class `node_encrypt::certificates` is declared:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'puppet_authorization::rule' at /etc/puppetlabs/code/environments/production/modules/node_encrypt/manifests/certificates.pp:66:7 on node my-puppetmaster.example.com
```

Note that Puppet Enterprise provides a resource `pe_puppet_authorization::rule` while Open Source Puppet provides `puppet_authorization::rule`

As a work-around, we have set the `node_encrypt::certificates`  parameter `$legacy` to `true`.

The resulting `auth.conf` file (without any additions from `node_encrypt::certificates` ) is sufficient for using `node_encrypt` on Puppet Enterprise.

**Comment by binford2k** [comment]
Do you have the `puppet_authorization` module installed, as per https://github.com/binford2k/binford2k-node_encrypt/blob/12e5579c6e0ad47910b18096633c96981fa5dbaf/metadata.json#L12 ?

**Comment by binford2k** [comment]
Assuming user error due to missing dependency. Please reopen if that's not the case.
