### ISSUE TITLE
Decrypt's OpenSSL::PKCS7::NOCHAIN verify fails if CA is intermediate

### ISSUE THREAD

**Issue by gabe-sky** [binford2k/binford2k-node_encrypt#29]
Briefly, node_decrypt currently fails to verify the signature of data if the CA is an intermediate, unless the fourth argument is changed to OpenSSL::PKCS7::NOVERIFY.  Switching to NOVERIFY seems to provide the same assurance that the data we're decrypting came from the same CA that the agent trusts.

In lib/puppet_x/binford2k/node_encrypt.rb, we verify that the signature on the data is valid, doing this:

  verify(nil, store, nil, OpenSSL::PKCS7::NOCHAIN)

The NOCHAIN invocation checks that the signature is valid, and further requires that the signer's certificate itself is valid.  Coming from a self-signed CA, the signer's certificate is valid because it's the root of the chain.  On a CA acting as an intermediate, the CA's certificate lacks enough information to verify the whole way up the chain, for some reason.

An alternative to NOCHAIN is NOVERIFY.  A bit of a misnomer, NOVERIFY does actually verify that the signature is valid on the data, but does not add the further requirement that the signer's certificate itself be valid.  Switching to NOVERIFY results in the verify succeeding when the CA is an intermediate.

I believe that NOVERIFY provides the same assurance that the agent is receiving encrypted data from the CA that its agent trusts, and that there is no need to use the NOCHAIN, here.

**Comment by gabe-sky** [comment]
More information on the difference between NOCHAIN and NOVERIFY here:

  https://www.openssl.org/docs/crypto/PKCS7_verify.html

**Comment by binford2k** [comment]
Question for you. Did you combine the external root CA cert with the intermediate cert according to step 2 at https://puppet.com/docs/puppet/5.3/config_ssl_external_ca.html#option-2-puppet-server-functioning-as-an-intermediate-ca?

**Comment by gabe-sky** [comment]
Yeah, @ipcrm assured me that the root was included in there, as required by NOCHAIN, which made it especially puzzling.

**Comment by binford2k** [comment]
addressed in #46
