### ISSUE TITLE
information sharing between nodes

### ISSUE THREAD

**Issue by binford2k** [binford2k/binford2k-node_encrypt#30]
There are certain use cases in which it would be helpful to share a small bit of data between nodes securely. Think a shared secret, for example, that's generated dynamically on the first start of a service that needs to be installed on each consumer of that service, for example.

The proposed workflow is a directory like `$confdir/node_encrypt.d/` that would work like `facts.d`, except each generated fact would be encrypted, and probably stored in a `$node_encrypted` structured fact. Then code meant for other nodes could either use that in a `node_encrypt::file` resource or invoke a (not-yet-written) `decrypt()` function to include it in a template or some such. (the latter option would result it being stored unencrypted in the catalog, so it would require a further call to `encrypt()` on the entire file contents to prevent that.)

Not entirely sure this is a good idea.

**Comment by Nekototori** [comment]
Not sure that's necessarily better than a custom fact that encrypts the fact itself somehow, other than streamlining the decryption process.

I have a use case that involves a file rather than a fact, so that'd need to take the base64 of the file and convert it...store it...extract it elsewhere.

**Comment by binford2k** [comment]
That's exactly what I'm suggesting, except with a standardized encrypt/decrypt process that doesn't require each fact to re-implement the process and that doesn't require the secret to be plaintext anywhere.

The encrypted blob is plain text, so it would not need to be base64, and storing the value of a file (as long as it was small) would not be an utterly terrible use of a fact.

**Comment by binford2k** [comment]
out of scope
