### ISSUE TITLE
Puppet agent unable to decrypt encrypted value on Windows

### ISSUE THREAD

**Issue by dragan1979** [binford2k/binford2k-node_encrypt#33]
i'm trying to hide windows password from puppet agent output (it's shown as plain text)

Password is encrypted with hiera:

init.pp:

` 'password' => node_encrypt(lookup('password'))`

when running `puppet agent -t `i see encrypted password (which is good)
```
"dsc_password": {
          "user": "ja@ad.contoso.com",
          "password": "-----BEGIN PKCS7-----\nMIINAwYJKoZIhvcNAQcDoIIM9DCCDPACAQAxggKfMIICmwIBADCBgjB9MXsweQYD\nVQQDDHJQdXBwZXQgRW50ZXJwcmlzZSBDQSBnZW5lcmF0ZWQgb24gbXlwdXBwZXQt\neGwwZGJ5a212Z2xrYnl2eS5ldS13ZXN0LTEub3Bzd29ya3MtY20uaW8gYXQgKzIw\nMTgtMTEtMDIgMTQ6MDQ6MDAgKzAwMDACAQUwDQYJKoZIhvcNAQEBBQAEggIANxVo\nScawQ7uaUIOaL+rP5gpWMMXp1sc57fkZGL7U........

```

But puppet agent tried to set this encrypted password and, of course fails because it's long output

Is it possible to somehow `node_encrypt`  "on the fly" decrypts this password and set it as plain text, while it shows it in encrypted form. Sensitive(lookup('password'))`` shows password in plain text.

**Comment by binford2k** [comment]
If you run this with `--debug`, any chance that you see the error `Can only encrypt strings`?

Also, how are you encrypting the data in Hiera? Are you pre-encrypting with `node_encrypt` and committing that or are you using `hiera-eyaml`?

**Comment by binford2k** [comment]
Ah. I misread this the first time. Yes, in Puppet 3/4/5, the decryption must be handled by a custom resource provider. That's a ton of work, so the only one that was implemented was the `node_encrypt::file` type.

If you're on Puppet 6, the soon to be released version will support what you're looking for. It would look like this:

```Puppet
password => lookup('password').node_encrypt::secret
```
