### ISSUE TITLE
Warning that node_encrypt::file overrides its own parameter

### ISSUE THREAD

**Issue by danielparks** [binford2k/binford2k-node_encrypt#40]
> Attempt to override an already evaluated resource, defined at (file: …/site/profile/manifests/eyaml/private.pp, line: 9),
> with new values (file: …modules/node_encrypt/manifests/file.pp, line: 72)

https://github.com/binford2k/binford2k-node_encrypt/blob/6024eaa71c17116d4f9616a2540b5b69e89956fb/manifests/file.pp#L72

We don't need to do this when `node_encrypt::file` gets a `Sensitive` instead of a `String`.

**Comment by binford2k** [comment]
What Puppet version?

**Comment by binford2k** [comment]
With #46, I'm not sure I care anymore :trollface:
