### ISSUE TITLE
Images in README.md don't show up on the Forge

### ISSUE THREAD

**Issue by danielparks** [binford2k/binford2k-node_encrypt#50]
https://forge.puppet.com/binford2k/node_encrypt#overview is missing the Puppet version images.

**Comment by binford2k** [comment]
oh that's irritating. At least it shows the placeholder text!

**Comment by danielparks** [comment]
It seems like something that would be most cleanly fixed on the Forge side of things. It seems like it might involve a bit of effort, but I figured it wouldn't hurt to file a ticket: [FORGE-479|https://tickets.puppetlabs.com/browse/FORGE-479].
