### ISSUE TITLE
puppet server cannot load library when calling function

### ISSUE THREAD

**Issue by logicminds** [binford2k/binford2k-node_encrypt#8]
I think I am hitting this issue. https://tickets.puppetlabs.com/browse/SERVER-973

Using PE 3.8 with puppet server.

**Comment by logicminds** [comment]
We should distribute this as a gem as well to get around some of these issues.

**Comment by logicminds** [comment]
https://github.com/logicminds/node_encrypt_gem

I created this to see if this would fix my problem.  If it works I think this should be available on ruby gems as well. I don't want to maintain it though.  So just fork my repo and publish it with your name.

**Comment by binford2k** [comment]
I am actually unable to replicate this. The function works properly in every environment I've tried, and the type works properly except for the `autobefore` problem on 3.x.

PE 2015:
```
root@master:~ # puppet --version
4.3.2
root@master:~ # puppet resource package pe-puppetserver
package { 'pe-puppetserver':
  ensure => '2.2.40-1.el7',
}
```

PE 3.8:
```
root@master:~ # puppet --version
3.8.1 (Puppet Enterprise 3.8.1)
root@master:~ # puppet resource package pe-puppetserver
package { 'pe-puppetserver':
  ensure => '1.1.1-1.el6',
}
```

**Comment by binford2k** [comment]
If it does turn out to be something I need to fix, I will probably take the route of https://github.com/nanliu/puppet-archive/blob/766062a3465053ca8a326ea0b3c31648a49474a4/lib/puppet/provider/archive/default.rb#L1-L10

I don't like the idea of switching to a gem to work around something intended to be delivered in a module.

**Comment by logicminds** [comment]
@binford2k 

If you created the following code for an agent 

```puppet
file{'/tmp/test.txt':
   ensure => present,
   content => node_encrypt('supersecret')
}
```

Then on the agent ran `puppet agent --test` you are saying the puppetserver is able to load the function and library code properly?  

I believe you could also reproduce this using `puppetserver irb` then try loading `require 'puppet_x/binford2k/node_encrypt'`

Can you explain exactly how you are testing?

**Comment by binford2k** [comment]
```
root@master:~ # tail -n 12 /etc/puppetlabs/code/environments/production/manifests/site.pp
node default {
  # This is where you can declare classes for all nodes.
  # Example:
  #   class { 'my_class': }

  node_encrypt::file { '/tmp/foo':
    owner   => 'root',
    group   => 'root',
    content => 'This string will never appear in the catalog.',
  }
}

root@master:~ # rm -f /tmp/foo
root@master:~ # puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for master.puppetlabs.vm
Info: Applying configuration version '1458216062'
Notice: /Stage[main]/Main/Node[default]/Node_encrypt::File[/tmp/foo]/Node_encrypted_file[/tmp/foo]/ensure: created
Notice: Applied catalog in 25.59 seconds
root@master:~ # cat /tmp/foo
This string will never appear in the catalog.
```

```
root@master:~ # puppet --version
4.3.2
root@master:~ # puppet resource package pe-puppetserver
package { 'pe-puppetserver':
  ensure => '2.2.40-1.el7',
}
```

**Comment by logicminds** [comment]
Please try this instead.  I believe the type/ provider loads the code correctly but I am specifically complaining about functions which get loaded differently.

```
node default {
  # This is where you can declare classes for all nodes.
  # Example:
  #   class { 'my_class': }

 file { '/tmp/foo':
    owner   => 'root',
    group   => 'root',
    content => node_encrypt('This string will never appear in the catalog.'),
  }
}

**Comment by binford2k** [comment]
It is a defined type that uses the function internally. That's how I force it to execute on the master during compilation. https://github.com/binford2k/binford2k-node_encrypt/blob/master/manifests/file.pp#L63

**Comment by logicminds** [comment]
I think what might be happening is that because you are using the custom type in the defined type which loads the puppet_x library properly.  Then function works correctly because node_encrypt is already in the load path since the provider is loaded before the function. I still think there is a problem when you use the function by itself without the custom type involved.

**Comment by binford2k** [comment]
```
root@master:~ # tail -n 12 /etc/puppetlabs/code/environments/production/manifests/site.pp
node default {
  # This is where you can declare classes for all nodes.
  # Example:
  #   class { 'my_class': }

  file { '/tmp/foo':
    owner   => 'root',
    group   => 'root',
    content => node_encrypt('This string will never appear in the catalog.'),
  }
}

root@master:~ # rm -rf /tmp/foo
root@master:~ # puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for master.puppetlabs.vm
Info: Applying configuration version '1458269220'
Notice: /Stage[main]/Main/Node[default]/File[/tmp/foo]/ensure: defined content as '{md5}318ff8cb125e33c0bae13a836f08c2df'
Notice: Applied catalog in 11.05 seconds
root@master:~ # cat /tmp/foo
-----BEGIN PKCS7-----
MIILlQYJKoZIhvcNAQcDoIILhjCCC4ICAQAxggJJMIICRQIBADAvMCoxKDAmBgNV
BAMMH1B1cHBldCBDQTogbWFzdGVyLnB1cHBldGxhYnMudm0CAQIwCwYJKoZIhvcN
AQEBBIICAA7AycoOOk4gVLaPCFWatER4rpt6UGUW4p5Kt6lqSLBllADCOztA3TV5
...
root@master:~ # puppet --version
4.3.2
root@master:~ # puppet resource package pe-puppetserver
package { 'pe-puppetserver':
  ensure => '2.2.40-1.el7',
}
```

**Comment by binford2k** [comment]
@logicminds heyo. Circling back to this, is this related to #14 you think? Or was that just the lack of pluginsync that I suggested?

**Comment by logicminds** [comment]
It is related to #14 and very well could be the cause.  But if others are using this without having to install the gem I created than I guess it is just my environment.  I am no longer on 3.8 having just deployed 2016.04.2.  But I still install the gem because it was just automatic (puppet code).  

When you say lack of pluginsync?  Are you saying the puppetserver was not able to sync code to itself?

 I should also mention that I am in a super locked down environment where the umask is 077 by default which might be my issue.

**Comment by binford2k** [comment]
I was guessing that the problem of not being able to load the library code is because the master didn't pluginsync yet. I don't actually know for sure, it was conjecture.

**Comment by olifre** [comment]
I just submitted a PR which fixes this, and explains the underlying reason.
