### ISSUE TITLE
How to get node certificates?

### ISSUE THREAD

**Issue by otheus** [binford2k/binford2k-node_encrypt#80]
Greetings, 

I'd love to use this module for our team. Do you know how to get the node's certificates from the puppet server? The API didn't seem to provide this functionality. We don't use PuppetDB. The Foreman caches the most recent facts.

In case it isn't clear, the use case is: 

1. on my laptop, use the node's certificate to create an encrypted secret, 
2. add the secret to the puppet/node file / hiera-yaml file.
3. commit/push the yaml file to the git server, 
4. git-server  CI/CD processes checks it for correctness, and  then deploys the puppet files to the environment's directory on the puppet server. 
5. The node then periodically runs pupet agent which requests from the server to build and send its catalog for the node to the node. 
6. Your module would then decrypt the key ala Deferred function and the server's private key. Victory! 

How do I do step 1 without manually logging into the node to get that key? Consider that I cannot log into the node until puppet runs at least once. 

Thanks for your time.

**Comment by binford2k** [comment]
Right now the easiest way to do this is to set up a file mount on the CA node using https://github.com/binford2k/binford2k-node_encrypt#automatically-distributing-certificates-to-compile-servers

Then just classify your laptop like you would a compile server.

**Comment by otheus** [comment]
Thanks @binford2k Ben. I've tried to understand your documentation there, and it seems like we're approaching this from completely different ways. There also seems to be some confusion in basic terms.

* I don't know what you mean by a 'compile server'. 

* I don't even really know what you mean by a 'file mount'. If it is what I think it is, that's a really bad idea. 

* I also don't know why you're discussing a 'CA node'. OF course, I'm assuming that the "CA node" is always the puppet master, but idk.  

* "Agent" I assume means the puppet agent running on a target puppet node.

* "Server" when used without qualifiers could mean anything. Sometimes I think you mean it as the server that is the puppet-node on which the agent runs. But then you use "node". Documentation is hard. I do applaud your efforts.

* "making public certificates available for download by all nodes." Well, that's not a problem at all. They are, _public certificates_, right?  OK, you mention that a paragraph later, but even mentioning it is confusing. Or maybe I'm confused at your approach. idk.

* "Classify all your servers, including the CA or Primary Server, with this class. This will ensure that all server have all agents' public certificates."  That made no sense to me whatsoever. Why would all servers need all agent's pub-certs? And do _agents_ have public certificates?

So I _think_ what you are saying is this:
 * Add a ruby fact which exposes the puppet-node's public certificate
 * Set up the the development environment to also run a puppet agent. 
 * Classify all puppet nodes that are development environments so that your provided class can distribute all collected certificates to these development environments.

If I'm right, it skips a few steps. 
* What mechanism "synchronizes" all the node's certificate-facts? 
* At what point is that fact available to the development environment? That is, how much time and how many puppet-agent runs are required for a node's certificate to be usable by the development environment?

Since March, I and my colleagues came up with a simple CGI-based solution.  Perhaps I should include this as a patch to this module?

My assumption is that I should just rely directly on the puppet-master server, which necessarily has access to all the certificates of all the puppet-nodes you wish to develop and encrypt secretes for. The information is there, but apparently there is no cli tool or API call to get these. So I build my own. I've uploaded the script and supporting configuration here: https://gist.github.com/otheus/3cc713c227dee30a4a44c11cad364e22  In my private repo, I have a Dockerfile for testing and README file. 

The advantages to this approach are:
*  The certificates are not copied or synchronized -- they are retrieved when needed
*  The development environment does not need to be a puppet agent of the central puppet-server
*  There is no delay between the time a server has been initialized with its certificate and when the certficate can be used. Thus, the agent does not need to run puppet agent before being deployable with secrets.

**Comment by binford2k** [comment]
> Thanks @binford2k Ben. I've tried to understand your documentation there, and it seems like we're approaching this from completely different ways. There also seems to be some confusion in basic terms.
> 
> * I don't know what you mean by a 'compile server'.

https://puppet.com/docs/puppet/latest/server/scaling_puppet_server.html#creating-and-configuring-compilers

> * I don't even really know what you mean by a 'file mount'. If it is what I think it is, that's a really bad idea.

https://puppet.com/docs/puppet/latest/file_serving.html
Why do you think it's a bad idea to distribute public certificates via a file mount?

> * I also don't know why you're discussing a 'CA node'. OF course, I'm assuming that the "CA node" is always the puppet master, but idk.

Because the CA node is the certificate authority that has all the agents' public certificates to start with. This is often the same node as your primary server.

> * "Agent" I assume means the puppet agent running on a target puppet node.
> * "Server" when used without qualifiers could mean anything. Sometimes I think you mean it as the server that is the puppet-node on which the agent runs. But then you use "node". Documentation is hard. I do applaud your efforts.

When talking about a Puppet infrastructure, a "node" is any computer or other system participating in the infrastructure. A "server" is a node that is running the Puppet server.

> * "making public certificates available for download by all nodes." Well, that's not a problem at all. They are, _public certificates_, right?  OK, you mention that a paragraph later, but even mentioning it is confusing. Or maybe I'm confused at your approach. idk.
> * "Classify all your servers, including the CA or Primary Server, with this class. This will ensure that all server have all agents' public certificates."  That made no sense to me whatsoever. Why would all servers need all agent's pub-certs? And do _agents_ have public certificates?

How would a server be able to compile a catalog with agent encrypted secrets without having that agent's certificate?


> So I _think_ what you are saying is this:
> 
> * Add a ruby fact which exposes the puppet-node's public certificate

No. That fact already exists and is used by default so that in most workflows you don't need to use the certificate distribution mechanism. But since you're talking about out-of-band encrypting secrets, you don't have that fact in scope. Instead, you should simply classify the dev environment with `node_encrypt::certificates` like the docs say.

> * Set up the the development environment to also run a puppet agent.
> * Classify all puppet nodes that are development environments so that your provided class can distribute all collected certificates to these development environments.
> 
> If I'm right, it skips a few steps.
> 
> * What mechanism "synchronizes" all the node's certificate-facts?

As per the documentation I linked, the `node_encrypt::certificates` class is the mechanism.

> * At what point is that fact available to the development environment? That is, how much time and how many puppet-agent runs are required for a node's certificate to be usable by the development environment?

Every time the agent runs on a node that has certificates synced to it, it will be fully synced with all certificates that have been signed.
 
> Since March, I and my colleagues came up with a simple CGI-based solution. Perhaps I should include this as a patch to this module?
> 
> My assumption is that I should just rely directly on the puppet-master server, which necessarily has access to all the certificates of all the puppet-nodes you wish to develop and encrypt secretes for. The information is there, but apparently there is no cli tool or API call to get these. So I build my own. I've uploaded the script and supporting configuration here: https://gist.github.com/otheus/3cc713c227dee30a4a44c11cad364e22 In my private repo, I have a Dockerfile for testing and README file.
> 
> The advantages to this approach are:
> 
> * The certificates are not copied or synchronized -- they are retrieved when needed
> * The development environment does not need to be a puppet agent of the central puppet-server
> * There is no delay between the time a server has been initialized with its certificate and when the certficate can be used. Thus, the agent does not need to run puppet agent before being deployable with secrets.
